Server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    username: goods
    password: root
    url: jdbc:mysql://47.94.4.31:3306/goods?allowMultiQueries=true&characterEncoding=utf-8&useSSL=false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: yun520.xyz.entities
eureka:
#  修改主机名加ip地址
  instance:
    instance-id: payment-8002
    prefer-ip-address: true #访问路径可以显示ip
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
     defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/